[package]
name = "image-compression-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = { version = "0.25" }
imagequant = "4.3.4"
png = "0.17.16"